In [1]:
from pandas import read_excel, DataFrame

TmcHmcOhcNhc = read_excel("Syntropic_SRB_Andrew.xlsx", "TmcHmcOhcNhc")
TmcABCD = read_excel("Syntropic_SRB_Andrew.xlsx", "TmcABCD")

nfnAB_flxABCD_etfAB = read_excel("Syntropic_SRB_Andrew.xlsx", "nfnAB_flxABCD_etfAB")
nfnAB_flxABCD_etfAB.columns = nfnAB_flxABCD_etfAB.iloc[0].to_numpy()
nfnAB_flxABCD_etfAB = nfnAB_flxABCD_etfAB.drop([0])

# TmcHmcOhcNhc

In [2]:
data = []
for column in TmcHmcOhcNhc.columns:
    if column not in ["Genome", "Unnamed: 13", "Unnamed: 14"]:
        data.extend(list(zip(TmcHmcOhcNhc[column].tolist(), [column]*len(TmcHmcOhcNhc), TmcHmcOhcNhc["Genome"].tolist())))
TmcHmcOhcNhc_df = DataFrame(data)
TmcHmcOhcNhc_df.columns = ["GeneID", "Function", "GenomeID"]
TmcHmcOhcNhc_df

                    GeneID Function                                 GenomeID
0                        -     HmcA           Desulfobacterales_sp._PC51MH44
1    OEU67172.1 (atypical)     HmcA          Desulfobacterales_sp._S5133MH16
2                        -     HmcA                  Desulfosarcina_sp._BuS5
3               2512526948     HmcA           Desulfococcus_biacutus_KMRActS
4               2502442176     HmcA  Desulfonema_limicola_Jadebusen_DSM_2076
..                     ...      ...                                      ...
523                      -     NhcC                Seep-SRB1g_Ga0402010_bin2
524                      -     NhcC                Seep-SRB1g_Ga0402030_bin2
525                      -     NhcC                Seep-SRB1a_Ga0402057_bin2
526                      -     NhcC                Seep-SRB1a_Ga0402054_bin3
527                      -     NhcC                Seep-SRB1a_Ga0402080_bin2

[528 rows x 3 columns]

# TmcABCD

In [3]:
data = []
for column in TmcABCD.columns:
    if column not in ["Genome", "Narrative objt name"]:
        data.extend(list(zip(TmcABCD[column].tolist(), [column]*len(TmcABCD), TmcABCD["Genome"].tolist())))
TmcABCD_df = DataFrame(data)
TmcABCD_df.columns = ["GeneID", "Function", "GenomeID"]
TmcABCD_df

         GeneID Function                GenomeID
0             0     TmcA  Seep-SRB1a_sp013792055
1           NaN     TmcA                     NaN
2             0     TmcA    Eth-SRB1_sp004193555
3             0     TmcA    Eth-SRB2_sp004193595
4             0     TmcA    Seep-SRB2_sp00364560
..          ...      ...                     ...
250           0     TmcD      DTYH01 sp012961955
251  NVL90555.1     TmcD    JABXJX01 sp013375375
252         NaN     TmcD                     NaN
253         NaN     TmcD                     NaN
254  NVM21705.1     TmcD    JABXJW01 sp013375395

[255 rows x 3 columns]

# nfnAB_flxABCD_etfAB

In [7]:
data = []
for column in nfnAB_flxABCD_etfAB.columns:
    if column not in ["Organism", "Narrative objt name"]:
        data.extend(list(zip(nfnAB_flxABCD_etfAB[column].to_numpy(), [column]*len(nfnAB_flxABCD_etfAB), nfnAB_flxABCD_etfAB["Organism"].to_numpy())))
nfnAB_flxABCD_etfAB_df = DataFrame(data)
nfnAB_flxABCD_etfAB_df.columns = ["GeneID", "Function", "GenomeID"]
nfnAB_flxABCD_etfAB_df

         GeneID Function                                 GenomeID
0             -     nfnA           Desulfobacterales_sp._PC51MH44
1             -     nfnA          Desulfobacterales_sp._S5133MH16
2    2513992634     nfnA                  Desulfosarcina_sp._BuS5
3             -     nfnA           Desulfococcus_biacutus_KMRActS
4             -     nfnA  Desulfonema_limicola_Jadebusen_DSM_2076
..          ...      ...                                      ...
382         NaN      NaN                                 G37 SRB2
383         NaN      NaN                                 HotSeep1
384         NaN      NaN                                      NaN
385         NaN      NaN                                      NaN
386         NaN      NaN                                      NaN

[387 rows x 3 columns]